service:
  name: fp-ts-survey

functions: ${file(./resources/functions.yml)}
resources: ${file(./resources/resources.yml)}

provider:
  name: aws
  region: 'eu-central-1'
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  profile: 'opc-sandbox'
  environment:
    tableName: ${self:provider.stage}-${self:service.name}__table

  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
      Resource: 'arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:*'

custom:
  serverless-offline:
    httpPort: 4000

  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      dev:
        sources:
          - table: ${self:provider.environment.tableName}
            sources: ['.seeds/surveys.json', '.seeds/responses.json']

package:
  individually: true

plugins:
  - serverless-dynamodb-local
  - serverless-webpack
  - serverless-offline
  - serverless-pseudo-parameters
